services:
  node:
    build:
      context: ../backend/gameServer
      dockerfile: Dockerfile
    image: game-server
    container_name: game-server
    ports:
      - "3002:3002"
    volumes:
      - ../backend/gameServer:/app
      - /app/node_modules
    depends_on:
      - ai
  ai:
    build:
      context: ../backend/aiServer
      dockerfile: Dockerfile
    image: ai-server
    container_name: ai-server
    ports:
      - "3003:3003"
    volumes:
      - ../backend/aiServer:/app
